# Generated by Django 3.0.3 on 2020-02-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(default=1)),
                ('loop_index', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loops', to='plan.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_index', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plan.Exercise')),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='plan.Loop')),
            ],
        ),
    ]
